import pytest
import json
from playwright.sync_api import expect
from page_objects.search_page import SearchPage
from page_objects.response import StreamedResponse

@pytest.mark.ai_summary
class TestAISummary:
    def test_ai_summary_appears_for_question(self, search_page: SearchPage):
        """Verify AI Summary appears when a question is searched."""
        query = "What are the main sources of air pollution in Europe?"
        print(f"\nTesting query: {query}")
        search_page.search(query)
        
        # Wait for expanded state
        print("Waiting for AI summary to expand...")
        search_page.wait_for_ai_summary()
        
        expect(search_page.ai_summary_wrapper).to_be_visible()
        expect(search_page.ai_summary_content).to_be_visible()
        
        content = search_page.ai_summary_content.text_content()
        print(f"AI Summary content received (length: {len(content.strip())})")
        assert len(content.strip()) > 0

    def test_ai_summary_loading_state(self, search_page: SearchPage):
        """Verify loading state is shown while AI Summary is being generated."""
        query = "How does climate change affect biodiversity?"
        print(f"\nTesting loading state for query: {query}")
        
        search_page.search_input.fill(query)
        search_page.search_input.press("Enter")
        
        # Check loading state (might be brief)
        try:
            print("Checking for loading state...")
            expect(search_page.ai_summary_loading).to_be_visible(timeout=5000)
            print("Loading state visible.")
        except Exception:
            # If it's too fast, we might miss it
            print("Loading state not detected (too fast or missing).")
            pass
            
        search_page.wait_for_ai_summary()
        expect(search_page.ai_summary_loading).to_be_hidden()

    def test_ai_summary_read_more(self, search_page: SearchPage):
        """Verify 'Read more' button works and shows detailed content."""
        query = "What is the European Green Deal?"
        print(f"\nTesting 'Read more' for query: {query}")
        search_page.search(query)
        search_page.wait_for_ai_summary()
        
        expect(search_page.read_more_button).to_be_visible()
        print("Clicking 'Read more' button...")
        search_page.read_more_button.click()
        
        expect(search_page.detailed_content).to_be_visible()
        detailed_text = search_page.detailed_content.text_content()
        print(f"Detailed content received (length: {len(detailed_text.strip())})")
        assert len(detailed_text.strip()) > 0

    def test_ai_summary_disclaimer(self, search_page: SearchPage):
        """Verify disclaimer modal can be opened and contains expected text."""
        print(f"\nTesting disclaimer. Current URL: {search_page.page.url}")
        search_page.page.goto(search_page.page.url) # ensure clean state if needed
        # We need AI summary to be visible to see the header icons
        query = "pollution"
        print(f"Searching for '{query}' to show header icons...")
        search_page.search(query)
        search_page.wait_for_ai_summary()

        expect(search_page.disclaimer_trigger).to_be_visible()
        print("Opening disclaimer modal...")
        search_page.disclaimer_trigger.click()
        
        expect(search_page.disclaimer_modal).to_be_visible()
        expect(search_page.disclaimer_modal).to_contain_text("This response was generated by artificial intelligence")
        print("Disclaimer modal verified.")

